version: '3.7'
services:
  paack_go_rest_service:
    build:
      context: './pkg'
      dockerfile: Dockerfile
    image: ghcr.io/kenesparta/paack_go
    container_name: paack_go_rest_service
    env_file: .env
    volumes:
      - "./cities.txt:/app/cities.txt"
      - "./logs:/app/logs"
    restart: "no"
    ports:
      - "${APP_PORT}:${APP_PORT}"
