version: '3.7'
services:
  paack_go_rest_service:
    build:
      context: '.'
      dockerfile: Dockerfile
    image: ghcr.io/kenesparta/paack_go
    container_name: paack_go_rest_service
    env_file: .env
    volumes:
      - "cities.txt:."
    restart: "no"
    ports:
      - "${API_PORT}:${API_PORT}"
